add terraform auth vars

diff --git a/templates/release.yml b/templates/release.yml
--- a/templates/release.yml
+++ b/templates/release.yml
@@ -22,6 +22,16 @@ jobs:
         workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
         addSpnToEnvironment: true
         inlineScript: |
+            # Fail on errors, output every command and result to the log
+            set -e -x
+
+            # Set terraform auth variables
+            export ARM_CLIENT_ID=$servicePrincipalId
+            export ARM_CLIENT_SECRET=$servicePrincipalKey
+            export ARM_SUBSCRIPTION_ID=$(az account show --query id | xargs)
+            export ARM_TENANT_ID=$(az account show --query tenantId | xargs)
+
+            # Generate SAS Token to storage account
             endDate=`date -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
             sas=`az storage container generate-sas \
                 -n '$web' \
@@ -36,9 +46,6 @@ jobs:
             -backend-config="access_key=$sas" \
             -backend-config="storage_account_name=${{ parameters['storageAccountName'] }}" \
             -input=false 
-
-            # Fail on errors, output every command and result to the log
-            set -e -x
 
             # Generate a Terraform plan
             terraform plan \
